### ISSUE TITLE
Winelink installation failed on Raspberry 4 4GB with Raspbian bookworm x64

### ISSUE THREAD

**Issue by IngoTB303** [WheezyE/Winelink#81] opened 2023-11-06 22:13 UTC
+ run_detect_arch
++ uname -m
+ KARCH=aarch64
+ '[' aarch64 = aarch64 ']'
+ ARCH=ARM64
+ run_detect_os
+ '[' -e /etc/os-release ']'
+ OS_INFOFILE=/etc/os-release
+ source /etc/os-release
++ PRETTY_NAME='Debian GNU/Linux 12 (bookworm)'
++ NAME='Debian GNU/Linux'
++ VERSION_ID=12
++ VERSION='12 (bookworm)'
++ VERSION_CODENAME=bookworm
++ ID=debian
++ HOME_URL=https://www.debian.org/
++ SUPPORT_URL=https://www.debian.org/support
++ BUG_REPORT_URL=https://bugs.debian.org/
+ case $ARCH in
+ run_detect_rpi
+ grep -q Raspberry /proc/device-tree/model
++ cat /proc/cpuinfo
++ grep Revision
++ cut -d ' ' -f 2
+ local HEXREVISION=c03111
++ echo 'obase=2; ibase=16; C03111'
++ bc
+ local BINREVISION=110000000011000100010001
+ local COUNTBITS=24
+ ((  24 < 32  ))
+ local ZEROSNEEDED=8
++ printf '%08d\n' 0
+ local LEADINGZEROS=00000000
+ local REVCODE=00000000110000000011000100010001
+ local N=0
+ local O=0
+ local Q=0
+ local W=0
+ local w=0
+ local F=1
++ echo 'obase=16; ibase=2; 100'
++ bc
+ local MMM=4
++ echo 'obase=16; ibase=2; 0000'
++ bc
+ local CCCC=0
++ echo 'obase=16; ibase=2; 0011'
++ bc
+ local PPPP=3
++ echo 'obase=16; ibase=2; 00010001'
++ bc
+ local TTTTTTTT=11
++ echo 'obase=16; ibase=2; 0001'
++ bc
+ local RRRR=1
+ PI_OVERVOLTAGE=
+ PI_OTPPROGRAM=
+ PI_OTPREAD=
+ PI_WARRANTY=
+ PI_RAM=
+ PI_MANUFACTURER=
+ PI_PROCESSOR=
+ PI_TYPE=
+ PI_REVISION=
+ '[' 1 = 0 ']'
+ '[' 1 = 1 ']'
+ case $N in
+ PI_OVERVOLTAGE=allowed
+ case $O in
+ PI_OTPPROGRAM=allowed
+ case $Q in
+ PI_OTPREAD=allowed
+ case $W in
+ PI_WARRANTY=intact
+ case $MMM in
+ PI_RAM=4GB
+ case $CCCC in
+ PI_MANUFACTURER='Sony UK'
+ case $PPPP in
+ PI_PROCESSOR=BCM2711
+ case $TTTTTTTT in
+ PI_TYPE=4B
+ PI_REVISION=1.1
+ echo -e '\nRaspberry Pi Model 4B Rev 1.1 BCM2711 with 4GB of RAM. Manufactured by Sony UK.'
+ echo '(Overvoltage allowed. OTP programming allowed. OTP reading allowed. Warranty intact)'
+ '[' 4B = 4B ']'
+ SBC_SERIES=RPi4
+ echo -e '\nThis Pi is part of the RPi4 series.'
+ run_detect_othersbc
++ tr -d '\0'
+ local 'model=Raspberry Pi 4 Model B Rev 1.1'
+ '[' 'Raspberry Pi 4 Model B Rev 1.1' = 'OrangePi 4 LTS' ']'
+ '[' 'Raspberry Pi 4 Model B Rev 1.1' = 'OrangePi 4' ']'
+ echo -e '\nThis SBC is part of the RPi4 series.'
+ case $SBC_SERIES in
+ case $ID in
+ case $ARCH in
+ run_greeting 'RPi4 ARM64 ' 10 2.8 ''
+ local 'hardware=RPi4 ARM64 '
+ local tinst=10
+ local space=2.8
+ local arg=
+ clear
+ echo ''
+ echo '####################### Winlink & VARA Installer Script #######################'
+ echo '# Author: Eric Wiessner (KI7POL)                         System: RPi4 ARM64   #'
+ echo '# Version: 0.0099a                                 Install time: apx 10 min   #'
+ echo '#                                                Space required: apx 2.8 GB   #'
+ echo '# Credits:                                                                    #'
+ echo '#   The Box86 team (ptitSeb, pale, chills340, Itai-Nelken, Heasterian, et al) #'
+ echo '#   Esme '\''madewokherd'\'' Povirk (CodeWeavers) for adding functions to wine-mono #'
+ echo '#   Botspot for RPi kernel switching bash code. Chris Keller for Pat support. #'
+ echo '#   N7ACW, AD7HE, & KK6FVG for getting me started in ham radio.               #'
+ echo '#   KM4ACK & OH8STN for inspiration. K6ETA & DCJ21'\''s Winlink on Linux guides. #'
+ echo '#                                                                             #'
+ echo '# Donations:                                                                  #'
+ echo '#    Box86                        paypal.me/0ptitSeb                          #'
+ echo '#    madewokherd / CodeWeavers    codeweavers.com/crossover                   #'
+ echo '#    Wine / wine-mono             winehq.org/donate                           #'
+ echo '#                                                                             #'
+ echo '#    "My humanity is bound up in yours, for we can only be human together"    #'
+ echo '#                                                - Nelson Mandela             #'
+ echo '###############################################################################'
+ '[' '' = bap ']'
+ read -n 1 -s -r -p 'Press any key to continue . . .'
+ clear
+ run_checkdiskspace 2800
+ local reqSpaceMB=2800
+ reqSpace512Blocks=5468750
++ POSIXLY_CORRECT=1
++ df /home/ingo
++ awk 'NR==2 { print $4 }'
+ availSpace=102928912
+ ((  availSpace < reqSpace512Blocks  ))
+ run_downloadbox86 14113faa_RPi4
+ local version=14113faa_RPi4
+ '[' ARM64 == ARM64 ']'
+ sudo dpkg --add-architecture armhf
+ sudo apt-get update
+ sudo apt-get install libc6:armhf -y
+ sudo apt-get install p7zip-full -y
+ echo -e '\e[32mDownloading and installing Box86 . . .\e[0m'
+ mkdir downloads
+ cd downloads
+ mkdir box86
+ cd box86
+ sudo rm /usr/local/bin/box86
+ wget -q https://github.com/WheezyE/Winelink/raw/main/binaries/box86_14113faa_RPi4.7z
+ 7z x box86_14113faa_RPi4.7z -y -bsp0 -bso0
+ sudo cp box86_14113faa_RPi4/build/system/box86.conf /etc/binfmt.d/
+ sudo cp box86_14113faa_RPi4/build/box86 /usr/local/bin/box86
+ sudo chmod +x /usr/local/bin/box86
+ sudo mkdir /usr/lib/i386-linux-gnu/
+ sudo cp box86_14113faa_RPi4/x86lib/libgcc_s.so.1 box86_14113faa_RPi4/x86lib/libpng12.so.0 box86_14113faa_RPi4/x86lib/libstdc++.so.5 box86_14113faa_RPi4/x86lib/libstdc++.so.6 /usr/lib/i386-linux-gnu/
+ sudo systemctl restart systemd-binfmt
+ cd ..
+ cd ..
+ run_Sideload_i386wine devel 7.1 debian bookworm -1
+ local branch=devel
+ local version=7.1
+ local id=debian
+ local dist=bookworm
+ local tag=-1
++ wine --version
++ grep '7.1\b'
+ local WINEVER=
+ '[' '!' -z '' ']'
+ wineserver -k
+ rm -rf /home/ingo/.cache/wine
+ rm -rf /home/ingo/.local/share/applications/wine
+ rm -rf /home/ingo/wine-old
+ mv /home/ingo/wine /home/ingo/wine-old
+ rm -rf /home/ingo/.wine-old
+ mv /home/ingo/.wine /home/ingo/.wine-old
+ sudo mv /usr/local/bin/wine /usr/local/bin/wine-old
+ sudo mv /usr/local/bin/wineboot /usr/local/bin/wineboot-old
+ sudo mv /usr/local/bin/winecfg /usr/local/bin/winecfg-old
+ sudo mv /usr/local/bin/wineserver /usr/local/bin/wineserver-old
+ LNKB=https://dl.winehq.org/wine-builds/debian/dists/bookworm/main/binary-i386/
+ DEB_B1=wine-devel-i386_7.1~bookworm-1_i386.deb
+ DEB_B2=wine-devel_7.1~bookworm-1_i386.deb
+ mkdir downloads
+ cd downloads
+ echo -e '\e[32mDownloading wine . . .\e[0m'
+ wget -q https://dl.winehq.org/wine-builds/debian/dists/bookworm/main/binary-i386/wine-devel-i386_7.1~bookworm-1_i386.deb
+ wget -q https://dl.winehq.org/wine-builds/debian/dists/bookworm/main/binary-i386/wine-devel_7.1~bookworm-1_i386.deb
+ echo -e '\e[32mExtracting wine . . .\e[0m'
+ dpkg-deb -x wine-devel-i386_7.1~bookworm-1_i386.deb wine-installer
+ dpkg-deb -x wine-devel_7.1~bookworm-1_i386.deb wine-installer
+ echo -e '\e[32mInstalling wine . . .\e[0m\n'
+ mv wine-installer/opt/wine-devel /home/ingo/wine
+ cd ..
+ echo -e '#!/bin/bash\nsetarch linux32 -L /home/ingo/wine/bin/wine "$@"'
+ sudo tee -a /usr/local/bin/wine
+ sudo ln -s /home/ingo/wine/bin/wineboot /usr/local/bin/wineboot
+ sudo ln -s /home/ingo/wine/bin/winecfg /usr/local/bin/winecfg
+ sudo ln -s /home/ingo/wine/bin/wineserver /usr/local/bin/wineserver
+ sudo chmod +x /usr/local/bin/wine /usr/local/bin/wineboot /usr/local/bin/winecfg /usr/local/bin/wineserver
+ run_Install_i386wineDependencies_RpiOS64bit
+ echo -e '\e[32mInstalling armhf dependencies for i386-Wine on aarch64 . . .\e[0m'
+ sudo dpkg --add-architecture armhf
+ sudo apt-get update
+ sudo apt-get install -y libasound2:armhf libc6:armhf libglib2.0-0:armhf libgphoto2-6:armhf libgphoto2-port12:armhf libgstreamer-plugins-base1.0-0:armhf libgstreamer1.0-0:armhf libldap-2.4-2:armhf libopenal1:armhf libpcap0.8:armhf libpulse0:armhf libsane1:armhf libudev1:armhf libusb-1.0-0:armhf libvkd3d1:armhf libx11-6:armhf libxext6:armhf libasound2-plugins:armhf ocl-icd-libopencl1:armhf libncurses6:armhf libncurses5:armhf libcap2-bin:armhf libcups2:armhf libdbus-1-3:armhf libfontconfig1:armhf libfreetype6:armhf libglu1-mesa:armhf libglu1:armhf libgnutls30:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libodbc1:armhf libosmesa6:armhf libsdl2-2.0-0:armhf libv4l-0:armhf libxcomposite1:armhf libxcursor1:armhf libxfixes3:armhf libxi6:armhf libxinerama1:armhf libxrandr2:armhf libxrender1:armhf libxxf86vm1 libc6:armhf libcap2-bin:armhf x11-utils:armhf libxcomposite-dev:armhf
+ run_installwinetricks
+ sudo apt-get remove winetricks -y
+ sudo apt-get install cabextract -y
+ mkdir downloads
+ cd downloads
+ echo -e '\n\e[32mDownloading and installing winetricks . . .\e[0m\n'
+ sudo mv /usr/local/bin/winetricks /usr/local/bin/winetricks-old
+ wget -q https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
+ sudo chmod +x winetricks
+ sudo mv winetricks /usr/local/bin
+ cd ..
+ run_installahk
+ sudo apt-get install p7zip-full -y
+ mkdir downloads
+ cd downloads
+ echo -e '\n\e[32mDownloading AutoHotkey . . .\e[0m\n'
+ wget -q https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.36.02/AutoHotkey_1.1.36.02_setup.exe
+ 7z e AutoHotkey_1.1.36.02_setup.exe AutoHotkeyU32.exe -y -bsp0 -bso0
+ mkdir /home/ingo/winelink
+ mkdir /home/ingo/winelink/ahk
+ sudo mv AutoHotkeyU32.exe /home/ingo/winelink/ahk/AutoHotkey.exe
+ sudo chmod +x /home/ingo/winelink/ahk/AutoHotkey.exe
+ cd ..
+ run_setupwineprefix
+ local varaonly=
+ echo -e '\n\e[32mInitializing wineprefix.  This may take a moment . . .\e[0m\n'
+ rm -rf /home/ingo/.cache/wine
+ DISPLAY=0
+ WINEARCH=win32
+ WINEDEBUG=-all
+ wine wineboot
+ '[' '' = vara_only ']'
+ echo -e '\n\e[32mSetting up your wineprefix for RMS Express & VARA . . .\e[0m\n'
+ run_installwinemono
+ '[' -d /home/ingo/.wine/drive_c/windows/Microsoft.NET/Framework/v4.0.30319 ']'
+ sudo apt-get install p7zip-full -y
+ mkdir /home/ingo/.cache/wine
+ echo -e '\n\e[32mDownloading and installing wine-mono . . .\e[0m\n'
+ wget -q -P /home/ingo/.cache/wine https://dl.winehq.org/wine/wine-mono/7.2.0/wine-mono-7.2.0-x86.msi
+ wine msiexec /i /home/ingo/.cache/wine/wine-mono-7.2.0-x86.msi
+ rm -rf /home/ingo/.cache/wine
+ wineboot -e
+ wineboot -f
+ wineserver -k
+ BOX86_DYNAREC=0
+ BOX86_NOBANNER=1
+ winetricks -q vb6run pdh_nt4 win7 sound=alsa
+ echo 'Winetricks failed to download/install VB6 or PDH.DLL!'
+ run_giveup
+ wineserver -k
+ echo ''
+ echo 'Winelink installation failed.'
+ echo ''
+ echo -e 'If a download failed, please check your internet connection and try re-running \nthe script.'
+ echo 'For help, please reference the '\''/home/ingo/winelink\winelink.log'\'' file'
+ echo 'You can also open an issue on github.com/WheezyE/Winelink/'
+ echo ''
+ set +x

Error messages during the installation:

Note, selecting 'libglu1-mesa:armhf' instead of 'libglu1:armhf'
Package libldap-2.4-2:armhf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libldap-common

E: Package 'libldap-2.4-2:armhf' has no installation candidate
-------
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Box86 with Dynarec v0.2.7 14113faa built on Oct 10 2022 20:20:17
Error initializing native libfreetype.so.6 (last dlerror is libfreetype.so.6: cannot open shared object file: No such file or directory)
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Error initializing native libfreetype.so.6 (last dlerror is libfreetype.so.6: cannot open shared object file: No such file or directory)
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Box86 with Dynarec v0.2.7 14113faa built on Oct 10 2022 20:20:17
Error initializing native libfreetype.so.6 (last dlerror is libfreetype.so.6: cannot open shared object file: No such file or directory)
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
----------------
installed_file1="Error initializing native libfreetype.so.6 (last dlerror is libfreetype.so.6: cannot open shared object file: No such file or directory)
Error initializing native libfreetype.so.6 (last dlerror is libfreetype.so.6: cannot open shared object file: No such file or directory)
------------------------------------------------------
warning: bug: w_metadata art2kmin corrupt, might need forward slashes?
------------------------------------------------------
Winetricks failed to download/install VB6 or PDH.DLL!
Box86 with Dynarec v0.2.7 14113faa built on Oct 10 2022 20:20:17

Winelink installation failed.

If a download failed, please check your internet connection and try re-running 
the script.

**Comment by mcmonagle101** [comment] 2023-12-04 22:26
The problem is line 62 of the installation script.
It wants to install libldap-2.4.2:armhf .
That version does not exist in bookworm.
That kill the entire "apt-get install"  causing massive failures latter on.
Change that to libldap-2.5-0:armhf.
I downloaded the script, edited it then ran it.
It's working for me.

**Comment by IngoTB303** [comment] 2023-12-05 05:58
Hi, many thanks, I will try it out later. 73

Am 4. Dezember 2023 23:26:49 MEZ schrieb mcmonagle101 ***@***.***>:

**Comment by mcmonagle101** [comment] 2023-12-24 17:23
My edit is on line 662 not 62. Sorry :-(

Trying  install on rpi5. 
See I have a bit more work ahead.

**Comment by WheezyE** [comment] 2024-07-25 23:38
Implementing the pi-apps wine install instead of my manual ("side-loaded") wine install should be more stable now and will be updated often by gman (on the pi-apps team). Please re-open this issue if you continue to have problems. I'm going to close this for now.

**Closed by WheezyE** 2024-07-25 23:38 UTC
