### ISSUE TITLE
Cannot Post a New Message to the Outbox or Save it to Drafts

### ISSUE THREAD

**Issue by KD2ROS** [WheezyE/Winelink#13] opened 2021-10-31 13:13 UTC
The new installation protocol works well in many ways...you do not repeatedly restart the application or wine...big win in my book...
But..in addition to the current issue where desktop icons for Vara, Vara FM and Winlink do not work after you shut down the initial installation launch session, you also cannot post to the outbox or save to drafts from the New Message window...even when in the initial launch session...it seems to start the post/save process, but it gets "stuck" and the little hourglass will happily spin until you close or cancel the new message session...

**Comment by WheezyE** [comment] 2021-11-01 01:10
Ahhh hm that’s not great. Thanks for letting me know. I’ll have to do more
debugging to see if I can track down that problem.  I thought I’d noticed a
Telnet message get downloaded but not appear in my inbox.

As a side-note: I’m happy to report that we just got ARDOP working this
evening. That fix should be able to be pushed by next week maybe (as soon
as the dev version of the new wine-mono .msi gets pushed as a stable
version to the wine-mono GitHub).

Thank you again for letting me know. I’ll try to get on this ASAP but it
might it might take a bit.

73!

**Comment by KD2ROS** [comment] 2021-11-01 01:33
Thanks Eric! I wish I could do more to help!

73

**Comment by WheezyE** [comment] 2021-11-02 02:29
I think I've found the culprit. I've submitted a bug report to the wine-mono dev, madewokherd, to see if they can work their magic.  Thank you again for your support

**Comment by WheezyE** [comment] 2021-11-06 23:22
Good news. Madewokherd fixed the 'Post to Outbox' error with https://github.com/madewokherd/wine-mono/pull/123.  Their fix has been applied in commit 8827ca3 of Winelink. Good looking-out.

Are Telnet messages receiving for you? I'm not sure messages are being received for me.

I also think I've found a few more bugs and am trying to track them down too.  Please let me know if you find more

**Comment by WheezyE** [comment] 2021-11-06 23:31
Ah, confirmed I can't receive yet. I'll keep digging!

```
[00000024:] EXCEPTION handling: System.MissingMethodException: Method 'System.String.Chars' not found.
```

**Comment by KD2ROS** [comment] 2021-11-07 13:16
I also have confirmed that I am not receiving any messages in my inbox…I can see them coming in normally in the active session window, but they are not populating the Inbox…

One piece of good news is that I can create and send messages and they populate the Sent Items system folder

73 de KD2ROS
Kate

**Comment by KD2ROS** [comment] 2021-11-07 14:39
Further explanation…I can see that the messages are indeed being received…all the message info, ID, bytes received, BYTES, Time and bytes/minute can be seen in the session code…BUT, none of this makes it into the Inbox system folder…if I knew how to retrieve the messages that were received but not put into the system folder Inbox I would still be happy…You are SO close to a stable product! I have not had to reboot Wine or my Pi4 since you've made these latest changes!

I have set my preferences to automatically forward any winlink messages that come in, to my Gmail account….I will let you know if this works….

Fingers Crossed,
Kate

**Comment by KD2ROS** [comment] 2021-11-07 15:00
Auto forwarding received winlink messages WORKS! This doesn’t fulfill the full expectations of Winlink functionality but it does get you about half the way…

Kate

**Comment by WheezyE** [comment] 2021-11-08 14:35
Thanks for testing things out a bit. Madewokherd has been wonderfully responsive with debugging wine-mono. We’ll see if they can fix this inbox error too.

I ran into some crashes when ARDOP is open too long and when I use the channel selection browser, but I’m really glad to hear you haven’t had as many crashes with wine-mono as we had with dotnet

73 de KI7POL
Eric

**Comment by WheezyE** [comment] 2021-11-18 06:38
@KD2ROS We've been trying to track down this inbox error for a while, but it's still eluding us.  This is a strange request, but would it be possible to post some of the text from your `C:\RMS Express\KD2ROS\Data\Registry.txt` file from a Windows machine for just a few messages in your inbox that were received via radio (not from telnet) just if you happened to have any on hand?  I'm wondering if the `Telnet:cms.Winlink.org` in my inbox messages is somehow causing parsing errors and some kind of wrench in the works for populating the inbox with entries from the Registry.txt file.

**Comment by KD2ROS** [comment] 2021-11-18 11:56
Here you go….Hope this helps! R358ZBKXZP492021/11/10 10:22KC2OQVKC2OQV2False|False|||||1223HV Winlink Thursday Reminder - Week 70 - Veteran's Day EditionRead ItemsCFalseRMS:N2GWKKC2VTJ...0Received202111101208417106500N86LT2LVZ01D2021/11/09 17:17KB4KYKB4KY2False|False|||||1717FINAL NET REPORT FOR THE AMLEG POST 42 WINLINK NET SESSION # 023 11/02/2021Read ItemsCFalseRMS:N2GWKAB4WS...0Received20211110121853710650059XDQXHT4XSG2021/11/09 16:17KN4LQNKN4LQN2False|False|||||3445Winlink Wednesday Reminder (#270)Read ***@***.***/11/10 12:25KD2ROSKD2ROS2False|True||||False|225Winlink Wednesday Check-InSent ItemsCFalseKN4LQN0Sent2021111012283810135000A96816FV2VX02021/11/18 01:44KC2OQVKC2OQV2False|False|||||1023HV Winlink Thursday Reminder - Week 71Read ItemsCFalseRMS:KD2ROS-10KC2VTJ...0Received202111181151030M430RJDH261E2021/11/15 23:14KC2OQVKC2OQV2False|False|||||1812FW: HV Winlink Thursday Results - Week 70 - Veteran's Day EditionRead ItemsCFalseRMS:KD2ROS-10KC2VTJ...0Received2021111811510404ZJKCMDNZOGD2021/11/16 14:35KN4LQNKN4LQN2False|False|||||3578Winlink Wednesday Reminder (#271)Read ***@***.*** 73 de KD2ROSKate   From: Eric Wiessner (KI7POL)Sent: Thursday, November 18, 2021 1:39 AMTo: WheezyE/WinelinkCc: KD2ROS; MentionSubject: Re: [WheezyE/Winelink] Cannot Post a New Message to the Outbox or Save it to Drafts (Issue ***@***.*** We've been trying to track down this inbox error for a while, but it's still eluding us. This is a strange request, but would it be possible to post some of the text from your C:\RMS Express\KD2ROS\Data\Registry.txt file from a Windows machine for just a few messages in your inbox that were received via radio (not from telnet) just if you happened to have any on hand? I'm wondering if the Telnet:cms.Winlink.org in my inbox messages is somehow causing parsing errors and some kind of wrench in the works for populating the inbox with entries from the Registry.txt file.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WheezyE** [comment] 2021-11-19 18:51
Thank you! That is helpful

**Comment by WheezyE** [comment] 2021-11-24 02:52
@KD2ROS Thank you again for your beta testing.  Great news!  Madewokherd was able to find and fix the inbox error too!

So looks like messages can be created now and received now.  I'll close this thread tomorrow.
73!

**Closed** 2021-11-25 19:17 UTC
